import Head from 'next/head'
import Image from 'next/image';
import Header from './../components/header';
import AboutMy from './../components/aboutMy';
import MyWorks from './../components/myWorks';
import ContactUs from './../components/contactUs';
import Footer from './../components/footer';

export default function Home() {
  return (
    <div className='home'  >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header/>
        <AboutMy/>
        <MyWorks/>
        <ContactUs/>
        <Footer/>
        
      </main>

    </div>
  )
}
